spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: url-shortener
            username: admin
            password: admin
            authentication-database: admin
            auto-index-creation: true